name: M450-starter
services:
  db:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: m450_starter_project
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: back-end.dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: unless-stopped
    stdin_open: true
    tty: true
  web:
    build:
      context: .
      dockerfile: front-end.dockerfile
    depends_on:
      - api
